version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    volumes:
      - "${LOCAL_DIR}/hub.docker:/var/lib/registry"

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"